### PR TITLE
Fix daily quest progress tracking

### LINKED ISSUE #926: [BUG] Fix every quest type progress
Estimated time: 4hs development + 2hs review 
 
- You always see the quest progress from previous days as 0 instead of the amount of quests that you completed
- When you complete a quest the milestone type quests are not being progressed

Example:
Yesterday I completed 5/6 quests
Today I see 0/6 from yesterday

Expected Behavior
I should have the dash (-) because I didn't completed the milestone for yesterday but I should see 5/6

### PR DESCRIPTION
**Pull request by AminArria**
## Motivation

Closes #926 

## Summary of changes

- Change to preload all quests for the week
- Filter out quests from not today when calculating progress

## How to test it?

The following steps assume you are starting from clean DB (`mix ecto.reset`)
1. Create a new user (easier to login with Unity)
2. Run the following SQL to move the daily quests to yesterday
```sql
update users set last_daily_quest_generation_at = '2024-09-12 17:00:00';

update user_quests set activated_at = '2024-09-12 17:00:00', inserted_at= '2024-09-12 17:00:00', updated_at= '2024-09-12 17:00:00';

-- The line below could potentially mark the milestone quest as completed, but regardless I don't think its an issue
update user_quests set status = (case when random() < 0.5 then 'completed' else 'available' end) ;
```
3. Login again through Unity to create todays quests

Now if you go to the quests tab you will see yesterday completed progress. Try to complete some from today to make sure everything still works as expected

## Checklist
- [x] Tested the changes locally.
- [x] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

File: apps/game_backend/lib/game_backend/users.ex [hunk 1]
```diff
@@ -168,24 +168,19 @@ defmodule GameBackend.Users do
...
-    {:ok, end_of_week_naive} = NaiveDateTime.new(end_of_week, ~T[23:59:59])
+    end_of_week_naive = NaiveDateTime.add(start_of_week_naive, 7, :day)
 
     quests_subquery =
       from(user_quest in UserQuest,
         as: :user_quest,
         join: quest in assoc(user_quest, :quest),
         as: :quest,
         where:
-          (quest.type in ^["daily", "milestone"] and user_quest.inserted_at > ^start_of_date and
```
Comment (AminArria) [inline apps/game_backend/lib/game_backend/users.ex:185]: This was the main culprit for the `0/6` error, it was preventing the fetching of previous day quests so as a result it was always showing as 0

**Review by agustinesco — APPROVED** [review]
LGTM! tested with yesterdays quests and is working

image

**Review by Nico-Sanchez — APPROVED** [review]
