### PR TITLE
[GH-767] Fix items and power ups spawning outside of the map

### LINKED ISSUE #767: Fix power ups and items spawning outside of the map boundaries

### PR DESCRIPTION
**Pull request by agustinesco**
## Motivation

When we spawned an item or a power up they could spawn a little bit outside of the map boundaries so you can't pick them up.
This was due to our random position generation solving the position only if it's outside of the map, even if the majority of the area is outside of it 

Closes #767

## Summary of changes

- Always resolver collision when generating random positions instead of checking map inclussion

## How to test it?

Start a match and kill some players close to the map boundaries, every power up should spawn in a pickupeable position, the same should happen to items

## Checklist
- [x] Tested the changes locally.
- [x] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

File: apps/arena/lib/arena/game_updater.ex [hunk 1]
```diff
@@ -1552,24 +1552,15 @@ defmodule Arena.GameUpdater do
       name: "Circle 1"
     }
 
-    entities_to_collide_with =
+    static_obstacles =
```
Comment (Nico-Sanchez) [inline apps/arena/lib/arena/game_updater.ex:1555]: Shouldn't we add active dynamic obstacles here?

File: apps/arena/lib/arena/game_updater.ex [hunk 2]
```diff
@@ -1552,24 +1552,15 @@ defmodule Arena.GameUpdater do
...
       Map.filter(obstacles, fn {_obstacle_id, obstacle} -> obstacle.aditional_info.type == "static" end)
-      |> Map.merge(%{external_wall.id => external_wall})
-
-    external_wall_id = external_wall.id
-
-    case Physics.check_collisions(circle, entities_to_collide_with) do
-      [^external_wall_id | []] ->
```
Comment (Nico-Sanchez) [inline apps/arena/lib/arena/game_updater.ex:1562]: Why was this check here? Are we losing an edge case handler by removing this?

**Review by Nico-Sanchez — CHANGES_REQUESTED** [review]
Liftable entities can spawn inside dynamic obstacles still, I believe we have to include those.

File: apps/arena/lib/arena/game_updater.ex (hunk 2 above)
Comment (agustinesco) [reply apps/arena/lib/arena/game_updater.ex:1562]: This was something used by the recursive implementation and caused trouble in both errors:
- Infinite loop
- Items spawning outside of the map

File: apps/arena/lib/arena/game_updater.ex (hunk 1 above)
Comment (agustinesco) [reply apps/arena/lib/arena/game_updater.ex:1555]: This was some creative freedom from our part, there could be some risk in taking power ups in spikes about to go up, if you think this looks more like a bug than a feature i could change it

Comment (Nico-Sanchez) [reply apps/arena/lib/arena/game_updater.ex:1555]: Maybe I wasn't clear enough. I think we should add the dynamic obstacles that are ACTIVE (you can't pass through) so the liftable entity can't go through as well.
It's ok to ignore it if the obstacle is off (underground).

Comment (agustinesco) [reply apps/arena/lib/arena/game_updater.ex:1555]: oooh okey, fair enough

Comment (Nico-Sanchez) [reply apps/arena/lib/arena/game_updater.ex:1555]: You forgot to change the variable name

Comment (agustinesco) [reply apps/arena/lib/arena/game_updater.ex]: Whoops, fixed

**Review by Nico-Sanchez — APPROVED** [review]

**Review by tvillegas98 — APPROVED** [review]
Seems to work well!
