### PR TITLE
[GH-971-969] - Increase wall colliders and fix items not spawning inside the square

### LINKED ISSUE #969: [BUG] - Items are not sparning inside merliot's map
Probably it is related to the external walls

### LINKED ISSUE #971: [BUG] Valtimer the Merliot escapist
We have a problem with Merliot's external wall.
Since our external wall is a circle, we have a huge circle with 4 obstacles as our square sides.
Valtimer's teleport can go through obstacles, so he can escape from Merliot's square.

There are 2 possible solutions:

1. Make the external wall a square, that will serve as our Merliot square sides.
2. Enlarge the square obstacle sides, so Valtimer's teleport can't reach the other side.

1 is the proper solution but 2 is way faster. Both are good to go solutions.

### PR DESCRIPTION
**Pull request by tvillegas98**
## Motivation

Having an square walls, is causing some troubles with things that could appear beyond these walls

Closes #971
Closes #969 

## Summary of changes

- Increased map radius size
- Increased external walls size (almost duplicataed)
- Added an square wall field to map configurations

## How to test it?

- Play the game and check that the items spawns inside the square (you'll have to print the random position created in `random_position_in_square/5`  and check that they don't go over the walls)
- Check that valtimer is not able to go trough the external walls

## Checklist
- [x] Tested the changes locally.
- [ ] Reviewed the changes on GitHub, line by line.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

File: apps/arena/lib/arena/game_updater.ex [hunk 1]
```diff
@@ -1659,6 +1660,37 @@ defmodule Arena.GameUpdater do
...
+
+    collisionable_obstacles =
+      Map.filter(obstacles, fn {_obstacle_id, obstacle} -> obstacle.aditional_info.collisionable end)
+
+    Physics.get_closest_available_position(
+      circle.position,
+      circle,
+      external_wall,
+      collisionable_obstacles
+    )
```
Comment (Nico-Sanchez) [inline apps/arena/lib/arena/game_updater.ex:1691]: Let's put this inside a function so both power ups and items use the same logic.

**Review by Nico-Sanchez — CHANGES_REQUESTED** [review]
LGTM! Just a minor comment

File: apps/arena/lib/arena/game_updater.ex (hunk 1 above)
Comment (tvillegas98) [reply apps/arena/lib/arena/game_updater.ex]: done in [feat: modularize random position functions](https://github.com/lambdaclass/mirra_backend/pull/977/commits/218dfa85dc290beb4cb49997a605f67e80f368c7)

**Review by Nico-Sanchez — APPROVED** [review]
